# Generated by Django 4.2.6 on 2023-12-07 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(default='images/profiles/default.jpg', max_length=255)),
                ('creditCard', models.CharField(max_length=50, null=True)),
                ('token', models.CharField(max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('dimensionX', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dimensionY', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dimensionZ', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dimensionX', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dimensionY', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dimensionZ', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='selectedModules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartProduct', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cartproduct')),
                ('modules', models.ManyToManyField(to='app.module')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.client')),
                ('modulesForProducts', models.ManyToManyField(to='app.selectedmodules')),
            ],
        ),
        migrations.CreateModel(
            name='compatibleModules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modules', models.ManyToManyField(to='app.module')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
        migrations.CreateModel(
            name='CartRelation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cartProduct', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.cartproduct')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.client')),
            ],
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.product'),
        ),
    ]
