# Generated by Django 4.2.7 on 2023-12-09 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_module_pairs'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='modules',
            field=models.ManyToManyField(to='app.module'),
        ),
        migrations.AlterField(
            model_name='module',
            name='pairs',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
