# Generated by Django 4.2.7 on 2023-12-09 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cartproduct_modules_alter_module_pairs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='quantity',
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='moduleQuantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='productQuantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
