# Generated by Django 4.2.7 on 2023-12-09 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_cartproduct_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartproduct',
            old_name='productQuantity',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='moduleQuantity',
        ),
    ]
