# Generated by Django 4.2.6 on 2023-12-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_cartproduct_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(default='images/products/phone/phone.png', max_length=255),
        ),
    ]
