# Generated by Django 4.2.6 on 2024-08-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_cartproduct_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='dimensionX',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='dimensionY',
            new_name='y',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='dimensionZ',
            new_name='z',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='media_path',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='dimensionX',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='dimensionY',
            new_name='y',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='dimensionZ',
            new_name='z',
        ),
        migrations.AddField(
            model_name='module',
            name='media_path',
            field=models.CharField(default='images/products/phone/phone.png', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='x_svg_path',
            field=models.CharField(default='images/products/phone/phone.png', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='y_svg_path',
            field=models.CharField(default='images/products/phone/phone.png', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='z_svg_path',
            field=models.CharField(default='images/products/phone/phone.png', max_length=255),
        ),
    ]
