# Generated by Django 4.2.6 on 2024-08-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_dimensionx_module_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='media_path',
            field=models.CharField(default='images/models/default.png', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='media_path',
            field=models.CharField(default='images/products/defult.png', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='x_svg_path',
            field=models.CharField(default='images/products/defult.png', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='y_svg_path',
            field=models.CharField(default='images/products/defult.png', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='z_svg_path',
            field=models.CharField(default='images/products/defult.png', max_length=255),
        ),
    ]
