# Generated by Django 4.2.6 on 2024-08-21 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_module_media_path_alter_product_media_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('gif_path', models.CharField(default='images/products/defult.gif', max_length=255)),
                ('x_svg_path', models.CharField(default='images/products/defult.png', max_length=255)),
                ('y_svg_path', models.CharField(default='images/products/defult.png', max_length=255)),
                ('z_svg_path', models.CharField(default='images/products/defult.png', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='model',
        ),
        migrations.RemoveField(
            model_name='product',
            name='x_svg_path',
        ),
        migrations.RemoveField(
            model_name='product',
            name='y_svg_path',
        ),
        migrations.RemoveField(
            model_name='product',
            name='z_svg_path',
        ),
        migrations.AlterField(
            model_name='module',
            name='media_path',
            field=models.CharField(default='images/modules/default.png', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.type'),
        ),
    ]
