# Generated by Django 4.2.6 on 2024-08-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_type_remove_product_model_remove_product_x_svg_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
